export const FETCH_CHORES = 'fetch_chores'
export const FETCH_MESSAGES = 'fetch_messages'
export const FETCH_LANDLORD_MESSAGES = 'fetch_landlord_messages'
export const FETCH_PAYMENTS = 'fetch_payments'
export const FETCH_BILLS = 'fetch_bills'